### ISSUE TITLE
mods.toml file has not been correct for a few MC versions.

### ISSUE THREAD

**Issue by KiriCattus** [BlueDuckYT/Jolly-Boxes#1]
The mods.toml file is missing the following in 1.20.1 for certain:
- Mods name
- Incorrect version number
- Authors names
- Correct license
- Mod description
- Source link (though those never show up in game by default it's useful to have for crash reports to find their way back to the correct person/team)

![image](https://github.com/BlueDuckYT/Jolly-Boxes/assets/19393068/9b44cece-27e8-4cae-a6eb-7022290c57bb)

This repository also contains the wrong license file (the default MinecraftForge one) and credits for the MDK however the main branch does contain a partially updated mods.toml but has not been released as far as I'm aware.

**Comment by BlueDuckYT** [comment]
Just corrected this, uploading fixed version to Curseforge now.
